-- =====================================================================================
-- MathStrokes - initial schema
-- =====================================================================================
-- Design notes that matter for correctness:
--
--  * An attempt never points at live question rows for its content or its answer key.
--    attempt_questions / attempt_question_options hold an immutable SNAPSHOT taken when the
--    attempt starts, including is_correct and the marking configuration. A teacher editing or
--    archiving a question later can therefore never change a historical result.
--
--  * The server owns time. test_attempts.expires_at is written at start; every answer write and
--    the submission path compare against it. The client clock is never trusted.
--
--  * Marks are NUMERIC, never floating point, so partial-marking arithmetic is exact.
-- =====================================================================================

-- ---------------------------------------------------------------------------- identity
CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(40)  NOT NULL UNIQUE,
    description VARCHAR(200)
);

CREATE TABLE users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name            VARCHAR(120) NOT NULL,
    phone_number         VARCHAR(20)  NOT NULL,
    password_hash        VARCHAR(100) NOT NULL,
    security_question    VARCHAR(255),
    security_answer_hash VARCHAR(100),
    enabled              BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at        TIMESTAMPTZ,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_phone_number UNIQUE (phone_number),
    CONSTRAINT ck_users_phone_format CHECK (phone_number ~ '^[0-9]{10,15}$')
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE INDEX idx_user_roles_role ON user_roles (role_id);

-- Refresh tokens are stored hashed: a database leak cannot be replayed against the API.
CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id    VARCHAR(64)  NOT NULL UNIQUE,
    token_hash  VARCHAR(100) NOT NULL,
    user_id     BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    issued_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked_at  TIMESTAMPTZ,
    replaced_by VARCHAR(64),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_expires ON refresh_tokens (expires_at) WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------------------- catalogue
CREATE TABLE subjects (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL UNIQUE,
    code          VARCHAR(20)  NOT NULL UNIQUE,
    description   VARCHAR(500),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE chapters (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id    BIGINT       NOT NULL REFERENCES subjects (id) ON DELETE RESTRICT,
    name          VARCHAR(150) NOT NULL,
    description   VARCHAR(500),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_chapters_subject_name UNIQUE (subject_id, name)
);

CREATE INDEX idx_chapters_subject_active ON chapters (subject_id, active, display_order);

-- ---------------------------------------------------------------------- marking schemes
-- configuration is JSONB so a new marking rule needs no migration; MarkingConfig validates it
-- on write and the evaluation strategies read it through a typed view.
CREATE TABLE marking_schemes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL UNIQUE,
    description   VARCHAR(500),
    exam_pattern  VARCHAR(30)  NOT NULL,
    question_type VARCHAR(40)  NOT NULL,
    configuration JSONB        NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_marking_exam_pattern CHECK (exam_pattern IN ('JEE_MAIN', 'JEE_ADVANCED')),
    CONSTRAINT ck_marking_question_type CHECK (question_type IN ('SINGLE_CORRECT', 'MULTIPLE_CORRECT'))
);

-- At most one active scheme per (exam_pattern, question_type) so resolution is unambiguous.
CREATE UNIQUE INDEX uq_marking_active_per_combo
    ON marking_schemes (exam_pattern, question_type) WHERE active;

-- ----------------------------------------------------------------------- question bank
CREATE TABLE questions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id       BIGINT      NOT NULL REFERENCES subjects (id) ON DELETE RESTRICT,
    chapter_id       BIGINT      NOT NULL REFERENCES chapters (id) ON DELETE RESTRICT,
    exam_pattern     VARCHAR(30) NOT NULL,
    difficulty       VARCHAR(20) NOT NULL,
    question_type    VARCHAR(40) NOT NULL,
    -- LaTeX / plain-text source, never rendered HTML. KaTeX renders it at display time.
    question_content TEXT        NOT NULL,
    solution_content TEXT,
    status           VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    marking_scheme_id BIGINT     REFERENCES marking_schemes (id) ON DELETE SET NULL,
    created_by       BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    updated_by       BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    published_at     TIMESTAMPTZ,
    -- Bumped on every persisted change: Hibernate optimistic lock + human-visible revision number.
    version          INTEGER     NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_questions_exam_pattern CHECK (exam_pattern IN ('JEE_MAIN', 'JEE_ADVANCED')),
    CONSTRAINT ck_questions_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT ck_questions_type CHECK (question_type IN ('SINGLE_CORRECT', 'MULTIPLE_CORRECT')),
    CONSTRAINT ck_questions_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    CONSTRAINT ck_questions_content_not_blank CHECK (length(btrim(question_content)) > 0)
);

-- Drives the admin filter grid and, critically, the random test-generation draw.
CREATE INDEX idx_questions_bank_selection
    ON questions (chapter_id, exam_pattern, difficulty, status);
CREATE INDEX idx_questions_status_created ON questions (status, created_at DESC);
CREATE INDEX idx_questions_subject ON questions (subject_id);
CREATE INDEX idx_questions_created_by ON questions (created_by);

CREATE TABLE question_options (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id   BIGINT      NOT NULL REFERENCES questions (id) ON DELETE CASCADE,
    option_key    VARCHAR(5)  NOT NULL,
    content       TEXT        NOT NULL,
    display_order INTEGER     NOT NULL DEFAULT 0,
    is_correct    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_question_options_key UNIQUE (question_id, option_key),
    CONSTRAINT ck_question_options_content CHECK (length(btrim(content)) > 0)
);

CREATE INDEX idx_question_options_question ON question_options (question_id, display_order);

-- ------------------------------------------------------------------------------- tests
CREATE TABLE tests (
    id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                  VARCHAR(200) NOT NULL,
    description            VARCHAR(1000),
    subject_id             BIGINT       NOT NULL REFERENCES subjects (id) ON DELETE RESTRICT,
    chapter_id             BIGINT       NOT NULL REFERENCES chapters (id) ON DELETE RESTRICT,
    exam_pattern           VARCHAR(30)  NOT NULL,
    duration_minutes       INTEGER      NOT NULL DEFAULT 60,
    question_count         INTEGER      NOT NULL DEFAULT 25,
    generation_mode        VARCHAR(30)  NOT NULL DEFAULT 'FIXED_SET',
    -- Difficulty blueprint. NULL entries mean "no constraint on that band".
    easy_count             INTEGER,
    medium_count           INTEGER,
    hard_count             INTEGER,
    status                 VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    -- Only FIXED_SET tests form a fair ranking cohort; see docs/ARCHITECTURE.md.
    ranking_enabled        BOOLEAN      NOT NULL DEFAULT TRUE,
    max_attempts_per_student INTEGER    NOT NULL DEFAULT 1,
    created_by             BIGINT       REFERENCES users (id) ON DELETE SET NULL,
    published_at           TIMESTAMPTZ,
    closed_at              TIMESTAMPTZ,
    version                INTEGER      NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_tests_exam_pattern CHECK (exam_pattern IN ('JEE_MAIN', 'JEE_ADVANCED')),
    CONSTRAINT ck_tests_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'CLOSED', 'ARCHIVED')),
    CONSTRAINT ck_tests_generation_mode CHECK (generation_mode IN ('FIXED_SET', 'RANDOM_PER_ATTEMPT')),
    CONSTRAINT ck_tests_duration CHECK (duration_minutes BETWEEN 1 AND 600),
    CONSTRAINT ck_tests_question_count CHECK (question_count BETWEEN 1 AND 200),
    CONSTRAINT ck_tests_max_attempts CHECK (max_attempts_per_student BETWEEN 1 AND 100),
    CONSTRAINT ck_tests_difficulty_counts CHECK (
        COALESCE(easy_count, 0) >= 0 AND COALESCE(medium_count, 0) >= 0
        AND COALESCE(hard_count, 0) >= 0)
);

CREATE INDEX idx_tests_browse ON tests (status, chapter_id, exam_pattern);
CREATE INDEX idx_tests_subject_status ON tests (subject_id, status);

-- Materialised question set for FIXED_SET tests. Written once at publish time.
CREATE TABLE test_questions (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id        BIGINT      NOT NULL REFERENCES tests (id) ON DELETE CASCADE,
    question_id    BIGINT      NOT NULL REFERENCES questions (id) ON DELETE RESTRICT,
    question_order INTEGER     NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_test_questions_question UNIQUE (test_id, question_id),
    CONSTRAINT uq_test_questions_order UNIQUE (test_id, question_order),
    CONSTRAINT ck_test_questions_order CHECK (question_order > 0)
);

CREATE INDEX idx_test_questions_test ON test_questions (test_id, question_order);
CREATE INDEX idx_test_questions_question ON test_questions (question_id);

-- ---------------------------------------------------------------------------- attempts
CREATE TABLE test_attempts (
    id                      BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id              BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    test_id                 BIGINT      NOT NULL REFERENCES tests (id) ON DELETE RESTRICT,
    attempt_number          INTEGER     NOT NULL DEFAULT 1,
    status                  VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    started_at              TIMESTAMPTZ NOT NULL,
    -- Server-authoritative deadline. Written once, never extended.
    expires_at              TIMESTAMPTZ NOT NULL,
    submitted_at            TIMESTAMPTZ,
    evaluated_at            TIMESTAMPTZ,
    duration_minutes        INTEGER     NOT NULL,
    total_questions         INTEGER     NOT NULL,
    score                   NUMERIC(8, 2),
    max_score               NUMERIC(8, 2),
    negative_marks          NUMERIC(8, 2),
    correct_count           INTEGER,
    partially_correct_count INTEGER,
    incorrect_count         INTEGER,
    unanswered_count        INTEGER,
    attempted_count         INTEGER,
    accuracy                NUMERIC(5, 2),
    attempt_rate            NUMERIC(5, 2),
    time_taken_seconds      INTEGER,
    rank_position           INTEGER,
    total_candidates        INTEGER,
    percentile              NUMERIC(5, 2),
    version                 INTEGER     NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_attempts_status CHECK (
        status IN ('NOT_STARTED', 'ACTIVE', 'SUBMITTED', 'AUTO_SUBMITTED', 'EVALUATED')),
    CONSTRAINT ck_attempts_expiry CHECK (expires_at > started_at),
    CONSTRAINT uq_attempts_student_test_number UNIQUE (student_id, test_id, attempt_number)
);

-- A student may hold at most one live attempt on a test at a time. Enforced by the database so
-- two concurrent "start test" requests cannot both succeed.
CREATE UNIQUE INDEX uq_attempts_one_active_per_test
    ON test_attempts (student_id, test_id) WHERE status = 'ACTIVE';

CREATE INDEX idx_attempts_student_status ON test_attempts (student_id, status, started_at DESC);
-- Drives the scheduled sweep that finalises attempts whose clock ran out.
CREATE INDEX idx_attempts_expiry_sweep ON test_attempts (expires_at) WHERE status = 'ACTIVE';
-- Drives the ranking window query.
CREATE INDEX idx_attempts_ranking
    ON test_attempts (test_id, score DESC, correct_count DESC, incorrect_count, time_taken_seconds)
    WHERE status = 'EVALUATED';

-- ------------------------------------------------------------- immutable attempt snapshot
CREATE TABLE attempt_questions (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id       BIGINT      NOT NULL REFERENCES test_attempts (id) ON DELETE CASCADE,
    -- Reference only, for analytics. Content is NEVER read back through this FK at evaluation.
    question_id      BIGINT      NOT NULL REFERENCES questions (id) ON DELETE RESTRICT,
    question_order   INTEGER     NOT NULL,
    question_version INTEGER     NOT NULL,
    chapter_id       BIGINT      REFERENCES chapters (id) ON DELETE SET NULL,
    exam_pattern     VARCHAR(30) NOT NULL,
    difficulty       VARCHAR(20) NOT NULL,
    question_type    VARCHAR(40) NOT NULL,
    question_content TEXT        NOT NULL,
    solution_content TEXT,
    marking_scheme_id BIGINT     REFERENCES marking_schemes (id) ON DELETE SET NULL,
    marking_scheme_name VARCHAR(150),
    -- Snapshot of the scheme configuration in force when the attempt started.
    marking_config   JSONB       NOT NULL,
    max_marks        NUMERIC(8, 2) NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_attempt_questions_order UNIQUE (attempt_id, question_order),
    CONSTRAINT uq_attempt_questions_question UNIQUE (attempt_id, question_id)
);

CREATE INDEX idx_attempt_questions_attempt ON attempt_questions (attempt_id, question_order);
CREATE INDEX idx_attempt_questions_question ON attempt_questions (question_id);

CREATE TABLE attempt_question_options (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_question_id BIGINT      NOT NULL REFERENCES attempt_questions (id) ON DELETE CASCADE,
    source_option_id    BIGINT,
    option_key          VARCHAR(5)  NOT NULL,
    content             TEXT        NOT NULL,
    display_order       INTEGER     NOT NULL DEFAULT 0,
    -- The answer key as it stood at snapshot time. Never sent to a student before submission.
    is_correct          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_attempt_options_key UNIQUE (attempt_question_id, option_key)
);

CREATE INDEX idx_attempt_options_question
    ON attempt_question_options (attempt_question_id, display_order);

-- ----------------------------------------------------------------------------- answers
CREATE TABLE student_answers (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id          BIGINT      NOT NULL REFERENCES test_attempts (id) ON DELETE CASCADE,
    attempt_question_id BIGINT      NOT NULL REFERENCES attempt_questions (id) ON DELETE CASCADE,
    answer_status       VARCHAR(40) NOT NULL DEFAULT 'NOT_VISITED',
    visited             BOOLEAN     NOT NULL DEFAULT FALSE,
    marked_for_review   BOOLEAN     NOT NULL DEFAULT FALSE,
    -- Monotonic per-attempt counter sent by the client. A save carrying a sequence lower than
    -- the stored one is a late arrival from a flaky connection and is discarded, so an
    -- out-of-order autosave can never overwrite a newer answer.
    client_sequence     BIGINT      NOT NULL DEFAULT 0,
    answered_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_student_answers_question UNIQUE (attempt_question_id),
    CONSTRAINT ck_student_answers_status CHECK (answer_status IN (
        'NOT_VISITED', 'NOT_ANSWERED', 'ANSWERED', 'MARKED_FOR_REVIEW',
        'ANSWERED_AND_MARKED_FOR_REVIEW'))
);

CREATE INDEX idx_student_answers_attempt ON student_answers (attempt_id);

CREATE TABLE student_answer_options (
    id                         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_answer_id          BIGINT      NOT NULL
                                   REFERENCES student_answers (id) ON DELETE CASCADE,
    attempt_question_option_id BIGINT      NOT NULL
                                   REFERENCES attempt_question_options (id) ON DELETE CASCADE,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_student_answer_option UNIQUE (student_answer_id, attempt_question_option_id)
);

CREATE INDEX idx_student_answer_options_answer ON student_answer_options (student_answer_id);

-- ------------------------------------------------------------------ per-question results
CREATE TABLE question_attempt_results (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id            BIGINT        NOT NULL REFERENCES test_attempts (id) ON DELETE CASCADE,
    attempt_question_id   BIGINT        NOT NULL
                              REFERENCES attempt_questions (id) ON DELETE CASCADE,
    -- Denormalised so question-level analytics never has to join through the attempt snapshot.
    question_id           BIGINT        NOT NULL REFERENCES questions (id) ON DELETE RESTRICT,
    result_status         VARCHAR(30)   NOT NULL,
    marks_awarded         NUMERIC(8, 2) NOT NULL,
    max_marks             NUMERIC(8, 2) NOT NULL,
    selected_option_count INTEGER       NOT NULL DEFAULT 0,
    correct_option_count  INTEGER       NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    -- Guarantees evaluation is idempotent: a replayed submit cannot double-insert results.
    CONSTRAINT uq_question_result_per_question UNIQUE (attempt_question_id),
    CONSTRAINT ck_question_result_status CHECK (
        result_status IN ('CORRECT', 'PARTIALLY_CORRECT', 'INCORRECT', 'UNANSWERED'))
);

CREATE INDEX idx_question_results_attempt ON question_attempt_results (attempt_id);
-- Drives question difficulty / accuracy analytics.
CREATE INDEX idx_question_results_question ON question_attempt_results (question_id, result_status);
